/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./../components/layout/AppSidebar.vue')['default']
    Favorites: typeof import('./../components/files/Favorites.vue')['default']
    FileCard: typeof import('./../components/files/FileCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    QuickActions: typeof import('./../components/dashboard/QuickActions.vue')['default']
    RecentFiles: typeof import('./../components/files/RecentFiles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StorageCard: typeof import('./../components/files/StorageCard.vue')['default']
    Trash: typeof import('./../components/files/Trash.vue')['default']
    WelcomeBanner: typeof import('./../components/dashboard/WelcomeBanner.vue')['default']
  }
}
